# Generated by Django 3.2.9 on 2021-12-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
