# Generated by Django 3.2.9 on 2021-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0010_comment_follow_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='https://res.cloudinary.com/dss64y5cs/image/upload/v1638773686/dohcsimcuwsnidykyqfl.png', upload_to='images/'),
        ),
    ]
