# Generated by Django 3.2.9 on 2021-12-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/images/default.png', upload_to='images/'),
        ),
    ]
